### ISSUE TITLE
Enhancements to shipping rate setup

### ISSUE THREAD

**Issue by sumitverma** [ten24/slatwall#1318]
We should discuss about adding the following options:
- define shipping based on quantity. You should be able to define quantity based on global/product type/product/sku
- define rate for "each additional" lb/quantity

e.g.

1-5 qty/lb ==> $2
5-10 qty/lb ==> $10
Each additional qty/lb ==> $1

**Comment by ian-a-hickey** [comment]
That's funny.

**Comment by gregmoser** [comment]
@ian-a-hickey is this funny because it's 3 years old? :)

I guess we can probably close out this issue once you add your code.
