### ISSUE TITLE
Configure mail server settings from within Slatwall

### ISSUE THREAD

**Issue by marbetschar** [ten24/slatwall#1697]
It would be great if Slatwall would allow you to configure the E-Mail server settings from within itself - similar as it is done in mura (see screenshot).

Because there are situations where you do not have full control about the environment and/or you would like to have all configuration values inside the application itself.

If there is no custom configuration, Slatwall can still use the systems default.

![bildschirmfoto 2013-07-25 um 00 16 51](https://f.cloud.github.com/assets/392542/852319/c8162dbc-f4ae-11e2-8ea4-c68860698b6d.png)

**Comment by gregmoser** [comment]
FYI, this has been implemented
