### ISSUE TITLE
Running update calculated properties task on orders Out of Mem Error

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#1852]
It's trying to process just about 28k of records. Server started throwing a java.lang.OutOfMemoryError around page 9 of the smartlist so 1800 records or so.. Set the p:show to 100 in the task service to see if that would help, but it still crapped out around page 17 / 1700 records.   Tried p:show=20 and it dies at page 71 / 1420 records

Looks like there is a leak somewhere

**Comment by dzikakis** [comment]
This issue seems to be back on Lucee 4.5.4.017 :(  Memory heap just climbs and climbs till it brings down the server. Did you guys ever run into this one again?

**Comment by ten24git** [comment]
On Slatwall stable or BE?

Sumit Verma
Partner / Vice President | ten24, LLC
office: 877.886.5806 x 103 | mobile: 617.290.8214
www.ten24web.com | www.linkedin.com/in/sverma | twitter: blogonria

**Comment by dzikakis** [comment]
Stable.

**Comment by ten24git** [comment]
I don't think we have made any changes in stable for how calculated
property works.

**Comment by dzikakis** [comment]
I don't think you have made any changes either. It appears to be how Lucee is handling the large number of created objects in a single request... same general behavior I was seeing on ACF, but had disappeared on Railo 4.1

**Comment by chriskent** [comment]
I have seen similar memory issues when performing many ORM transactions in a single ORM session/CF request
Two  separate clients, one on ACF10 and other on ACF11 
Both import type processes
One fixed by limiting the number of base records to be imported in a batch and repeating the batch
One fixed by firing threads to process each import
