### ISSUE TITLE
Listing view tweaks needed 

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#1917]
On some listing views like accounts the filters are set up on things like phone number and email address. With over 15000 accounts, you can imagine how slow these filters are to load.  

I have a branch with a bunch of minor listing view tweaks, that I'll do a pull request for at some point. Just wanted to capture the issue first.

**Comment by sumitverma** [comment]
Lot of changes made to listing since this issue was reported. Collection listing is replacement for listing display.
