### ISSUE TITLE
Implicit Event Triggers not firing

### ISSUE THREAD

**Issue by cfaddict** [ten24/slatwall#2068]
I am unable to get any of the implicit events to fire. I updated the logging to show detailed logging and I see all of the implicit events logged such as

onApplicationSetup
onApplicationRequestStart
onApplicationRequestEnd

etc...

But if I setup a new trigger event for something simple like afterProductSaveSuccess and edit / save a product this trigger never happens. I never see the email go out and I never see this event logged.

**Comment by sumitverma** [comment]
This is resolved
