### ISSUE TITLE
Option codes don't populate properly?

### ISSUE THREAD

**Issue by ronnieduke** [ten24/slatwall#2073]
Maybe I'm missing something, but when you setup codes for product options such as "R" for Red, and "B" for Blue, I was expecting the skus to populate accordingly: 1122-R, 1122-B, etc. 

Right now, it just adds "1122-1", "1122-2" etc. Its not building by option code.

**Comment by orcpac7** [comment]
+1 for dzikakis suggestion that this enhancement, if added, either be configurable or broken out for easier modification.
