### ISSUE TITLE
Capture on order fulfillment showing when not necessary 

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#2103]
Minor thing.. When you're fulfilling items on an order you're presented with the "Capture pre-authorized CC" option even if the order doesn't have a CC payment associated with it (like in the case of a term payment). This seems innocuous, because it's easy to just click "no".  But if you have different people doing fulfillments and they don't know how the order has been paid, it's too easy for them to click 'no' to avoid the message below on a term order on an order that actually needs to have the capture go through!

![image](https://f.cloud.github.com/assets/474990/2249206/850cc2b0-9d82-11e3-8501-eabe21949fe9.png)

**Comment by sumitverma** [comment]
This is resolved
