### ISSUE TITLE
Partial delivery capturing entire auth amount

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#2121]
Even with 30f9acf after the pre-process, it shows the correct amount to capture, but then upon creation of the delivery it's capturing the full auth amount vs the partial amount. - don't have time to look at it right now, so wanted to make note here.

**Comment by dzikakis** [comment]
I don't think the functionality of a flag to allow partial captures or not was ever implemented, was it?

**Comment by gregmoser** [comment]
No... you just have to know if your integration can handle multi-capture or not.  Again, it should be implemented as a flag on the integration, and then based on that flag the admin UI should change to not allow the user to try and do a 'partial capture'.  Or at least it needs to say that you can only do 1 capture against this auth.
