### ISSUE TITLE
Feature Request: Image version tracking

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#2655]
It would be great to have a simple int value increment every time an image was updated on a product. This would allow for really simple cache defeating for services like amazon cloud front, by using this value on front end templates like:  productImage.png?v=1 / productImage.png?v=2

**Comment by gregmoser** [comment]
Couldn't you use getCreatedDateTime() or getModifiedDateTime()

**Comment by dzikakis** [comment]
Yes that totally works for basic cache defeating, but it's not super efficient given that the record of a sku or image may change multiple times without the actual file changing.

**Comment by gregmoser** [comment]
Are you talking about the default image filename that gets added to the sku record?  Because when that image is uploaded, we actually don't do anything in the DB.  It is just convention based.

**Comment by dzikakis** [comment]
Yes that and the swimages.. I know nothing happens in the DB on upload of sku default images, which is why some type of version # would be helpful in the DB.. If the images were bulk-uploaded there'd be no version number.
