### ISSUE TITLE
Element ACCOUNT is undefined in VARIABLES. 

### ISSUE THREAD

**Issue by wiredmonkey** [ten24/Slatwall#2826]
From time to time I get an error 'Element ACCOUNT is undefined in VARIABLES. ' on pages that don't use slatwall. Any idea how to fix? I've attached the errors.
http://www.wiredmonkey.co.uk/wiredmonkey/error.htm

Shaun

**Comment by cfaddict** [comment]
We had the same issue and the team submitted a fix for it here
https://github.com/ten24/Slatwall/commit/51ed29f4f0ccf3b4976bbfe33aa7e1fab3cb1fd0


Don't think its in the release yet

Thank You
Dan Vega
danvega@gmail.com
http://www.danvega.org/

**Comment by wiredmonkey** [comment]
Thanks Dan, much appreciated! I’ve applied the fix and hopefully that will be the last time I see that error.

Best

Shaun

**Comment by gregmoser** [comment]
This fix has been released as version 3.5.043
