### ISSUE TITLE
Error when renewing subscription with PayPal Express - ORDERPAYMENT missing

### ISSUE THREAD

**Issue by wiredmonkey** [ten24/slatwall#2841]
Hi

I'm receiving the following error message 'The ORDERPAYMENT parameter to the copyFromOrderPayment function is required but was not passed in.' when I click the 'Renew' button to renew a subscription. I've saved the full stack trace here - http://www.wiredmonkey.co.uk/wiredmonkey/my-account.htm Any ideas?

Cheers

Shaun

**Comment by gregmoser** [comment]
What version of Slatwall are you running?

**Comment by wiredmonkey** [comment]
I just updated to 3.5.043 and the issue still exists.

**Comment by gregmoser** [comment]
Ok, we'll take a look.  Thanks for reporting.

**Comment by wiredmonkey** [comment]
Hi Greg, any updates on this?

Thanks

Shaun

**Comment by gregmoser** [comment]
Actually @chriskent is putting together the final fix for this, and should have a hotfix in place very shortly.  I'll let Chris follow up if there is anything else.

**Comment by wiredmonkey** [comment]
Thanks for the update.

Shaun
