### ISSUE TITLE
Selectbox attribute field showing 'Select' and 'select' in options

### ISSUE THREAD

**Issue by wiredmonkey** [ten24/slatwall#2857]
I have a selectbox custom attribute field. I have set all the values, in the front-end it shows 'Select' and 'select' as the top options in the value list. See attached screengrab.

Cheers

Shaun
![edit-profile](https://cloud.githubusercontent.com/assets/950788/6080345/2c555398-ae08-11e4-9e19-83d948dbacb1.png)

**Comment by gregmoser** [comment]
Are you sure that you don't have an attributeOption called "Select"?  We recently made changes so that "Select" gets added by default.  You may have added one manually before.

**Comment by wiredmonkey** [comment]
Definitely not, I've checked each select attribute and I've never added a default option.
