### ISSUE TITLE
AddressForm case senstive

### ISSUE THREAD

**Issue by brucebailey** [ten24/slatwall#2866]
AddressForm.cfm refers to sw:formField and should be sw:FormField
AddressForm.cfm refers to sw:errorDisplay and should be sw:ErrorDisplay

**Comment by Squeebly-Joe** [comment]
/public/tags/AddressForm.cfm still has sw:errorDisplay instead of sw:ErrorDisplay. This causes issues on Linux systems.

**Comment by gregmoser** [comment]
If you guys just want to issue a PR with this fix we would gladly accept it.
