### ISSUE TITLE
Multiple Promotions are not applied

### ISSUE THREAD

**Issue by marbetschar** [ten24/slatwall#2936]
Multiple promotions can be added to cart, but they are not applied (see screenshot):

![xlzp_rabatt](https://cloud.githubusercontent.com/assets/392542/6320107/f3b2ff9c-bad5-11e4-892e-622750e64e75.JPG)

Even in the promotions settings there is no limit configured.
Slatwall Version used: 3.4.026

**Comment by gregmoser** [comment]
This has been resolved in the very latest hotfix release today.
