### ISSUE TITLE
No matching function [SETTING] found

### ISSUE THREAD

**Issue by marbetschar** [ten24/slatwall#2937]
Slatwall v3.4.026 is occasionally throwing the following error in our checkout process:

Catch
additional	
Struct
Entities	
string	SlatwallPromotionPeriod, SlatwallTaxApplied, SlatwallAccountPaymentApplied, SlatwallPaymentMethod, SlatwallStockAdjustmentDelivery, SlatwallSchedule, SlatwallPromotionApplied, SlatwallTaskSchedule, SlatwallUpdateScript, SlatwallReport, SlatwallPaymentTransaction, SlatwallFile, SlatwallOrderPayment, SlatwallShippingMethodRate, SlatwallPromotionReward, SlatwallAccount, SlatwallPermissionGroup, SlatwallLoyalty, SlatwallSubscriptionUsage, SlatwallCategory, SlatwallAccountPayment, SlatwallSetting, SlatwallPromotion, SlatwallAccess, SlatwallAccountRelationship, SlatwallOption, SlatwallOrderReturn, SlatwallSite, SlatwallAccountContentAccess, SlatwallSkuCurrency, SlatwallTaxCategory, SlatwallPromotionAccount, SlatwallSubscriptionBenefit, SlatwallOrderDeliveryItem, SlatwallVendorOrder, SlatwallEventTrigger, SlatwallSku, SlatwallPhysicalCountItem, SlatwallStock, SlatwallShortReference, SlatwallFileRelationship, SlatwallEmailVerification, SlatwallAttributeOption, SlatwallVendorOrderItem, SlatwallBrand, SlatwallStockAdjustment, SlatwallOrderItem, SlatwallInventory, SlatwallEmail, SlatwallPrint, SlatwallOrderDelivery, SlatwallTaskHistory, SlatwallLocation, SlatwallStockAdjustmentItem, SlatwallAudit, SlatwallCurrency, SlatwallTask, SlatwallProductReview, SlatwallAccountEmailAddress, SlatwallAddressZone, SlatwallPrintTemplate, SlatwallAccountLoyaltyTransaction, SlatwallAttributeValue, SlatwallIntegration, SlatwallSession, SlatwallCountry, SlatwallTerm, SlatwallTaxCategoryRate, SlatwallAccountPaymentMethod, SlatwallVendorSkuStock, SlatwallType, SlatwallPromotionQualifier, SlatwallVendorEmailAddress, SlatwallCommentRelationship, SlatwallComment, SlatwallOrderOrigin, SlatwallOrder, SlatwallAccountAuthentication, SlatwallPhysical, SlatwallProductType, SlatwallSubscriptionStatus, SlatwallStockHold, SlatwallLocationAddress, SlatwallVendorAddress, SlatwallAttributeSet, SlatwallRoundingRule, SlatwallSubscriptionUsageBenefitAccount, SlatwallVendorPhoneNumber, SlatwallProduct, SlatwallShippingMethod, SlatwallAccountLoyalty, SlatwallAccountAddress, SlatwallAddress, SlatwallMeasurementUnit, SlatwallAccountPhoneNumber, SlatwallVendorAccount, SlatwallSubscriptionTerm, SlatwallStockReceiver, SlatwallContentAccess, SlatwallIntegrationS3Request, SlatwallPriceGroup, SlatwallAttribute, SlatwallLoyaltyAccruement, SlatwallLoyaltyTerm, SlatwallVendor, SlatwallSubscriptionOrderItem, SlatwallFulfillmentMethod, SlatwallPostalCode, SlatwallShippingMethodOption, SlatwallPromotionCode, SlatwallEmailTemplate, SlatwallState, SlatwallPermission, SlatwallImage, SlatwallAlternateSkuCode, SlatwallPhysicalCount, SlatwallSubscriptionUsageBenefit, SlatwallContent, SlatwallOptionGroup, SlatwallStockReceiverItem, SlatwallPaymentTerm, SlatwallOrderFulfillment, SlatwallPriceGroupRate, SlatwallLoyaltyRedemption, SlatwallStockAdjustmentDeliveryItem
_Datasource	
string	gpro_erohypnose
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	No matching function [SETTING] found
StackTrace	
string	No matching function [SETTING] found at railo.runtime.orm.hibernate.event.EventListener.invoke(EventListener.java:86):86 at railo.runtime.orm.hibernate.event.InterceptorImpl.on(InterceptorImpl.java:60):60 at railo.runtime.orm.hibernate.event.InterceptorImpl.onSave(InterceptorImpl.java:41):41 at org.hibernate.event.def.AbstractSaveEventListener.substituteValuesIfNecessary(AbstractSaveEventListener.java:414):414 at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:293):293 at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:204):204 at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:144):144 at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:210):210 at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:195):195 at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:117):117 at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:93):93 at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:677):677 at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:669):669 at railo.runtime.orm.hibernate.HibernateORMSession.save(HibernateORMSession.java:144):144 at railo.runtime.functions.orm.EntitySave.call(EntitySave.java:15):15 at railo.runtime.functions.orm.EntitySave.call(EntitySave.java:11):11 at org.hibachi.hibachidao_cfc$cf.udfCall1(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiDAO.cfc:51):51 at org.hibachi.hibachidao_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiDAO.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:199):199 at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624 at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506 at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1749):1749 at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:739):739 at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1481):1481 at org.hibachi.hibachiservice_cfc$cf.udfCall1(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiService.cfc:170):170 at org.hibachi.hibachiservice_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiService.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:199):199 at railo.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:713):713 at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:739):739 at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1481):1481 at org.hibachi.hibachiservice_cfc$cf.udfCall3(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiService.cfc:573):573 at org.hibachi.hibachiservice_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiService.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.call(UDFImpl.java:212):212 at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:704):704 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:713):713 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1471):1471 at org.hibachi.hibachiservice_cfc$cf.udfCall1(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiService.cfc:284):284 at org.hibachi.hibachiservice_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiService.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.call(UDFImpl.java:212):212 at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623 at railo.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:547):547 at railo.runtime.ComponentImpl._call(ComponentImpl.java:508):508 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1732):1732 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:713):713 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1471):1471 at integrationservices.s3.model.service.integrations3requestservice_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\integrationServices\s3\model\service\IntegrationS3RequestService.cfc:52):52 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.call(UDFImpl.java:212):212 at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623 at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1732):1732 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:713):713 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1471):1471 at integrationservices.s3.controllers.public_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\integrationServices\s3\controllers\public.cfc:23):23 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:199):199 at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624 at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506 at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1749):1749 at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:739):739 at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:733):733 at railo.runtime.util.VariableUtilImpl.callFunction(VariableUtilImpl.java:699):699 at railo.runtime.interpreter.ref.func.UDFCall.getValue(UDFCall.java:47):47 at railo.runtime.interpreter.CFMLExpressionInterpreter.interpret(CFMLExpressionInterpreter.java:192):192 at railo.runtime.functions.dynamicEvaluation.Evaluate._call(Evaluate.java:91):91 at railo.runtime.functions.dynamicEvaluation.Evaluate.call(Evaluate.java:84):84 at railo.runtime.functions.dynamicEvaluation.Evaluate.call(Evaluate.java:25):25 at org.hibachi.fw1.framework_cfc$cf.udfCall7(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\FW1\framework.cfc:1197):1197 at org.hibachi.fw1.framework_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\FW1\framework.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.call(UDFImpl.java:212):212 at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:704):704 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:713):713 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1471):1471 at org.hibachi.fw1.framework_cfc$cf.udfCall4(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\FW1\framework.cfc:677):677 at org.hibachi.fw1.framework_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\FW1\framework.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.call(UDFImpl.java:212):212 at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:704):704 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:713):713 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1471):1471 at org.hibachi.hibachi_cfc$cf.udfCall2(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\Hibachi.cfc:604):604 at org.hibachi.hibachi_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\Hibachi.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.call(UDFImpl.java:212):212 at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623 at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1732):1732 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:713):713 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1471):1471 at org.hibachi.hibachiscope_cfc$cf.udfCall1(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiScope.cfc:94):94 at org.hibachi.hibachiscope_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\org\Hibachi\HibachiScope.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.call(UDFImpl.java:212):212 at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623 at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1732):1732 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:713):713 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1471):1471 at integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall1(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\integrationServices\mura\model\handler\MuraEventHandler.cfc:106):106 at integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\Slatwall\integrationServices\mura\model\handler\MuraEventHandler.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:199):199 at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624 at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506 at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1745):1745 at railo.runtime.tag.Invoke.doComponent(Invoke.java:203):203 at railo.runtime.tag.Invoke.doEndTag(Invoke.java:176):176 at plugin.pluginmanager_cfc$cf.udfCall3_000007(C:\inetpub\wwwroot\gpro_erohypnose\requirements\mura\plugin\pluginManager.cfc:1559):1559 at plugin.pluginmanager_cfc$cf.udfCall3(C:\inetpub\wwwroot\gpro_erohypnose\requirements\mura\plugin\pluginManager.cfc:1477):1477 at plugin.pluginmanager_cfc$cf.udfCall(C:\inetpub\wwwroot\gpro_erohypnose\requirements\mura\plugin\pluginManager.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:95):95 at railo.runtime.type.UDFImpl._call(UDFImpl.java:308):308 at railo.runtime.type.UDFImpl.call(UDFImpl.java:212):212 at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:704):704 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:713):713 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1471):1471 at plugin.pluginmanager_cfc$cf.udfCall3(C:\inetpub\wwwroot\gpro_erohypnose\requirements\mura\plugin\pluginManager.cfc:1253):1253 at

**Comment by gregmoser** [comment]
Two issues here.

1) Please update to the latest stable release before logging issues.  Often items like this have already been resolved.

2) This error looks like it is being thrown from a custom "s3" integration.

I believe that at one point there were some concurrency issues with the setting() function called from an integration, but those issues have been resolved in a more recent version.
