### ISSUE TITLE
Variable GETTYPESERVICE is undefined on OrderService.cfc:1443

### ISSUE THREAD

**Issue by wiredmonkey** [ten24/slatwall#3012]
Since I upgraded to slatwall 3.5.051 I'm getting an error when users are transferred back from paypal to the website to finalise their order. I hadn't seen this issue on our test site but now it's on our live site so I'm trying to revert the slatwall update. So any help would be much appreciated!

The full stack trace can be viewed here - http://www.wiredmonkey.co.uk/wiredmonkey/error.html

Shaun

**Comment by gregmoser** [comment]
What version are you on, I believe that this has been resolved already in a recent release

**Comment by wiredmonkey** [comment]
This was after upgrading to 3.5.0.51 last night, I noticed this morning that a few orders weren't showing as completed but the money was taken.

**Comment by gregmoser** [comment]
This has been resolved in a hotfix
