### ISSUE TITLE
Issue with tasks and audit service

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#3224]
When running the updateCalculated properties task on stocks/skus/products I discovered it was throwing an error - wit h little detail in the log, just:

START EXCEPTION
Log Exception Error

After a little digging, it appears that the issue is on https://github.com/ten24/slatwall/blob/master/org/Hibachi/HibachiAuditService.cfc#L716
It seems that the hibernate session is closed, not sure if that's because the task is run in a thread? And the call to the lazy loaded email throws a "no session" error.

As a simple fix, I just switched the account.cfc:getPrimaryEmailAddress to lazy="false" fetch="join" and it's working fine now.  There's likely a better/more elegant way to do this. Considered entityMerge, but there's a good chance the account would have been modified by some other process in the mean time on some of these super long running tasks (like updatecalculatedproperties)

**Comment by jsieber-aca** [comment]
Verified that this is also throwing a "no session error" for us on version 3.5.61.
