### ISSUE TITLE
Auto Fulfillment not working in v4.0.021?!

### ISSUE THREAD

**Issue by marbetschar** [ten24/slatwall#3326]
After Updating to v4.0.021 the live system stopped working! :(

For some reason the processOrderDelivery_create fails with the following error:

   arguments.entity.getErrors: {""processObjects"":[""create""]}"

And I can't see any reason why because the only eligible fullfillment method is "auto".
No others allowed, whether globally nor on SKU's.

No orders are completed and therefore no product information is sent to the customers :(

**Comment by marbetschar** [comment]
The code section in charge is the following in the orderService - any idea what's wrong?!

    if(
			arguments.orderFulfillment.getFulfillmentMethodType() == "auto" 
			&& (
				order.getTotal() == 0 
				|| orderFulfillment.getFulfillmentMethod().setting('fulfillmentMethodAutoMinReceivedPercentage') <= precisionEvaluate( order.getPaymentAmountReceivedTotal() * 100 / order.getTotal() ) 
			) 
		){
												
			// Setup the processData
			var processData = {};
			processData.order = {};
			processData.order.orderID = order.getOrderID();
			processData.location.locationID = arguments.orderFulfillment.getFulfillmentMethod().setting('fulfillmentMethodAutoLocation');
			processData.orderFulfillment.orderFulfillmentID = arguments.orderFulfillment.getOrderFulfillmentID();
			
			newOrderDelivery = this.processOrderDelivery(newOrderDelivery, processData, 'create');
		}

Any help would highly be appreciated!!!

**Comment by rmarchandTen24** [comment]
this has been patched in 4.0.023

**Comment by marbetschar** [comment]
Seems to be fixed after updating to 4.0.23.
But I ran into another problem: https://erotische-hypnose.com/feminisierung/

Is this anyhow related? How can this be fixed?

**Comment by sumitverma** [comment]
Not related. This is coming from your product template. You should debug
there and see what's the issue.

Sumit Verma
Partner / Vice President | ten24, LLC
office: 877.886.5806 x 103 | mobile: 617.290.8214
www.ten24web.com | www.linkedin.com/in/sverma | twitter: blogonria

**Comment by marbetschar** [comment]
Ok; I'll digg into it! Thanks for the help anyways!!
