### ISSUE TITLE
Export Slatwall Account incl. E-Mail Adress

### ISSUE THREAD

**Issue by marbetschar** [ten24/slatwall#3335]
I've programmed a Slatwall integration which lists a bunch of Slatwall Accounts and their E-Mail address.
Now I'd like to export the whole list containing the E-Mail Adress.

Unfortunately when I call the ?slatAction=entity.exportSlatwallAccount endpoint, the full list WITHOUT email address is beeing exported.

How to add the email to the exported CSV?

**Comment by gregmoser** [comment]
Marco, we try to use github for 'issues' this is expected behavior.  I believe that exporting data is part of collections in version 4.1 where you can configure collections to hold whatever data you like.  In the future please post questions like this to the google group.

**Comment by marbetschar** [comment]
@gregmoser Ok, sure! Thank you very much!!
