### ISSUE TITLE
Error email appears blank at least in gmail.

### ISSUE THREAD

**Issue by jsieber-aca** [ten24/slatwall#3343]
When I configure the errorNotifyEmailAddresses in configFramework.cfm I receive an error email, but in gmail it is blank. If I view the original source I can see the css, javascript and html for the cfdump, but it won't render in the actual email. Removing the cfmailpart tags resolves the issue.

**Comment by gregmoser** [comment]
Very interesting... do you get the 3 dots in gmail that look like this: http://screencast.com/t/AeZATfyRMAT

**Comment by jsieber-aca** [comment]
Actually, we get nothing. 
http://screencast.com/t/e7KbU6N5yLT

I removed the cfmailpart tags and the email comes through as expected.

**Comment by jsieber-aca** [comment]
Created a pull request with the fix we put in place in our environment.
https://github.com/ten24/slatwall/pull/3379
