### ISSUE TITLE
Password validation gives incorrect message

### ISSUE THREAD

**Issue by jsieber-aca** [ten24/slatwall#3363]
Version 4.0.023

When creating a password from the view account screen there appears to be a minimum character amount when creating a new password, but the error given is the following, which is incorrect and misleading. 

The value entered for Password should be alphanumeric with no spaces.

The specific error should describe the the actual issue causing the validation to fail.

**Comment by gregmoser** [comment]
This is a great point.  I'm not sure why the error isn't more descriptive.  Someone just needs to update the RB file.

**Comment by gregmoser** [comment]
Actually I just checked and this is already fixed in v4... you probably saw this on a v3.5 right?

**Comment by jsieber-aca** [comment]
We tested on version 4.0.023 and still noticed the issue.

**Comment by rmarchandTen24** [comment]
the only instance you should get this is if the specific rbkey is not found. Then it defaults to validate.define.regex=The value entered for ${propertyName} should be alphanumeric with no spaces.

There is only one other instance of alphanumeric and it exists on the product level so it can't be that.

can you check to see that you have rb keys for

validate.changePassword.Account_ChangePassword.password.minLength or
validate.changePassword.Account_ChangePassword.password.regex

**Comment by rmarchandTen24** [comment]
ah i see, we are missing validate.createPassword.Account_CreatePassword.password.regex. I'll put it in.

**Comment by jsieber-aca** [comment]
Thanks Ryan!
