### ISSUE TITLE
Order Items missing with fullfillment "auto" (v4.0.023)

### ISSUE THREAD

**Issue by marbetschar** [ten24/slatwall#3421]
Using Slatwall v4.0.023 the order items are missing.

It's not possible to see, which products a customer has ordered in a specific order as the loading bar just spins infinitely:

![bildschirmfoto 2015-07-02 um 21 35 38](https://cloud.githubusercontent.com/assets/392542/8486086/8ff2a370-2102-11e5-9173-a5cb857e2470.png)

What can we do to fix the issue?

**Comment by rmarchandTen24** [comment]
Hi Marco,

I just need a little more info for this one. Can you open up the developer tools and check for either a console error or a network error?

**Comment by marbetschar** [comment]
Hi @rmarchandTen24 

Thanks for getting back to me on this one. I just checked the dev tools and indeed there are some errors visible:

![bildschirmfoto 2015-07-22 um 11 48 45](https://cloud.githubusercontent.com/assets/392542/8822720/c10ebf92-3067-11e5-84e7-c7df04bf38c0.png)

![bildschirmfoto 2015-07-22 um 11 49 06](https://cloud.githubusercontent.com/assets/392542/8822723/c639a5fe-3067-11e5-9d19-1e620e74f360.png)

Hope this helps in debugging the issue? Please let me know if you need anything else!

**Comment by rmarchandTen24** [comment]
Can you show the response on the red items?

Ryan

**Comment by marbetschar** [comment]
Sure:

<img width="1280" alt="bildschirmfoto 2015-07-22 um 19 22 13" src="https://cloud.githubusercontent.com/assets/392542/8832060/014901c8-30a7-11e5-89c0-cebf4dae3653.png">

**Comment by marbetschar** [comment]
Any News in this one?

**Comment by rmarchandTen24** [comment]
Hi Marco,

Sorry, Marco I still need more details. If you click on the red items in
the developer tools and then click the response tab, what does it say? Have
you tried updating to 4.1?
