### ISSUE TITLE
Error when creating account - you have called a method geteventRegistration() which does not exists in the Account entity.

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#3438]
Perhaps I'm being dim today, but I can't figure out why I've never seen this error before, as it seems it would always happen.

https://drive.google.com/file/d/0B--HzsYeNo7bb1JlSWlkTmQyckk/view?usp=sharing

**Comment by jasperboyd** [comment]
I'm not able to read the stack trace it looks like google compressed the image

**Comment by dzikakis** [comment]
If you download it (top-middle) button, you can view it full-size.

**Comment by jasperboyd** [comment]
was able to recreate it, fix is coming soon

**Comment by dzikakis** [comment]
Nice. Just glad I'm not going crazy.
