### ISSUE TITLE
Recurring Event Schedule (monthly, week of the month)

### ISSUE THREAD

**Issue by CatherineMortali** [ten24/slatwall#3502]
When adding a recurring event as Monthly > Week of the Month (i.e. 1st Tuesday), it defaults to the Day of the Month (i.e., the 6th of the month).

Thanks!

**Comment by davidpanzarella** [comment]
@CatherineMortali I believe they are aware of this, and it's due to be fixed in 4.2. (don't quote me on that though! :) )

**Comment by gregmoser** [comment]
@CatherineMortali & @davidpanzarella I don't believe that we have this planned for the 4.2 release as a fix right now.  If it is a high priority item for either of you please let Emily know.

Thanks,
Greg
