### ISSUE TITLE
Status of Available Stable Version says "Connection Failure"

### ISSUE THREAD

**Issue by davidpanzarella** [ten24/slatwall#3568]
I've seen this on a few sites and varied versions. Is it just down at the moment?

**Comment by gregmoser** [comment]
For security reasons we changed the version filename path and the pre 4.0
versions can't read it.  It will work you just need to update.

Latest stable is 4.1.005 I believe.  You can always look on github as well
under releases.

--
Greg Moser
Slatwall Product Manager | ten24 Digital Solutions
http://www.slatwallcommerce.com
http://www.ten24web.com

mobile  |  760.518.5314
office    |  877.886.5806 x107

**Comment by davidpanzarella** [comment]
Yup that's what i'm currently doing, just wasn't sure if you saw that or not. For the record, on one of these sites I'm on 4.1.006 and it still says connection failure. Just to clarify, is it always going to say connection failure, or are you presuming its just for those sites that have pre 4.0? I'm wondering if my version.cfm is still in the old path?

**Comment by gregmoser** [comment]
If you are on 4.1.006 and still getting 'connection failure' than that is a bug.  Can you add a screenshot of your upgrade screen?
