### ISSUE TITLE
Authorize.net's new API endpoint 

### ISSUE THREAD

**Issue by thebutterfly** [ten24/slatwall#3573]
Many carts are releasing updates and/or patches for this. Will Slatwall be releasing an update? If so, when should we expect it?

TY

**Comment by gregmoser** [comment]
I believe that we already point to the new endpoint and this issue can be closed, but I will let Ryan or Sumit confirm

**Comment by thebutterfly** [comment]
We (and our clients have as well) just have gotten hit with many Authorize.net's announcements and need to be sure that we have a plan to initiate any changes that are required, across the board. As many of the other carts that we work on have either specified the changes to be made or say that they are releasing updates in regards to them (Drupal Commerce, ProductCart, Cart66) I wanted to be sure where Slatwall was fitting in. I'm not surprised you're ahead of the curve! :)

**Comment by thebutterfly** [comment]
By the way: here is one of the things I was referencing: http://www.authorize.net/support/akamaifaqs/

**Comment by sumitverma** [comment]
Thanks for the link. So, looks like the only change is they are recommending using the new URL:

Old: https://secure.authorize.net/gateway/transact.dll

New: https://secure2.authorize.net/gateway/transact.dll

We will make that configurable, and default to new url.
