### ISSUE TITLE
Separate product options are now merged

### ISSUE THREAD

**Issue by pixelot1964** [ten24/slatwall#364]
I had size and image product options separate in earlier SW version, then on the last update 104-432 started combining them and makes for a huge list of options.  Instead of 2 option select menus, 1 for size and 1 for image like previously, now there is 1 select with each size and image combined.  Options should be unique.... Thanks!

**Comment by sumitverma** [comment]
Front-end has the ability to do option drop downs or use one consolidated. Sample template has code for both.
