### ISSUE TITLE
volume purchase discount table

### ISSUE THREAD

**Issue by zac123** [ten24/slatwall#374]
i'm not entirely sure how this would work but we'd like to be able to offer customers discounts for volumn purchases.

so, example.

buy 1 to 9 lolly pops and pay 0.50 each
buy 10 to 19 lolly pops and pay 0.45 each

this could then be displayed on the front end in a small table much the same as ebuyer.com:

http://www.ebuyer.com/130304-casecom-black-silver-trim-mid-tower-case-no-psu-kb-8890

scroll down a bit to see 'Price Breaks'

**Comment by sumitverma** [comment]
Quantity based pricing is in the current BE (4.5) and will be part of next release.
