### ISSUE TITLE
Print Templates and Permission Groups

### ISSUE THREAD

**Issue by StevePrescott** [ten24/slatwall#3844]
I've set up a print template used as a packing slip for orders placed.
On the order details screen I see the printer icon added to the navbar/action bar and I am able to print the packing slip so everything seems to be set up and working properly.

I also set up a Customer Service permission group and a test account that I've added to this group.
Even if I grant full data permissions to every option on the permission setting screen the test account is not able to print the packing slip unless I also make them a Super User. Otherwise the result is an Access Denied error in a "popup window" that then keeps attempting to open additional numerous Access Denied popup windows.

Steve

**Comment by rmarchandTen24** [comment]
https://github.com/ten24/slatwall/pull/3877 make sure the user has access to action admin:print.default as well. Fix will be in 4.2.004
