### ISSUE TITLE
save the transient instance before flushing: SlatwallAddress

### ISSUE THREAD

**Issue by wiredmonkey** [ten24/slatwall#3905]
Since I've upgraded to Slatwall 4.2.006 this evening. I'm receiving an error on the placeorder method "/check-out/?slatAction=public:cart.placeOrder"

Any ideas what could be causing this? I've attached the fullstack trace.

[www.gogivers.org.pdf](https://github.com/ten24/slatwall/files/69015/www.gogivers.org.pdf)

Cheers

Shaun

**Comment by rmarchandTen24** [comment]
error was specific to subscription orders

https://github.com/ten24/slatwall/compare/hotfix...hotfix-rm-subscriptionusageshippingaddressbug?expand=1

got a fix for 4.2.007
