### ISSUE TITLE
ColdFusion 12 Support

### ISSUE THREAD

**Issue by mcollins323** [ten24/slatwall#4028]
CF12 is now in Beta2 - can the Slatwall team test and confirm it works and is supported?

Thanks,
Mike Collins

**Comment by gregmoser** [comment]
I'm are not on the beta list for CF12, is there a download link somewhere?  Is this a public beta?

**Comment by mcollins323** [comment]
Greg - you should be getting an email soon with an invite.

Mike

**Comment by gregmoser** [comment]
Mike, I never got an email

**Comment by gregmoser** [comment]
This has been resolved in Slatwall 4.5
