### ISSUE TITLE
Account Address Custom Attribute Layout Bug

### ISSUE THREAD

**Issue by davidpanzarella** [ten24/slatwall#4043]
There appear to be a layout bug with Account Address Extended Attributes:

As you'll see in the image below the checkboxes are not clearing.
<img width="598" alt="screen shot 2016-01-29 at 9 48 42 pm" src="https://cloud.githubusercontent.com/assets/755283/12697042/8a910c06-c72d-11e5-9a61-05d73fd08e48.png">

**Comment by davidpanzarella** [comment]
Any update on this?

**Comment by gregmoser** [comment]
I believe this was fixed in release 4.2.016

Please test

**Comment by davidpanzarella** [comment]
Same output on 4.3.002

**Comment by gregmoser** [comment]
Looks perfect to me... http://screencast.com/t/PbekJta38

**Comment by davidpanzarella** [comment]
This is for Account Addresses. Can you try on that object?

**Comment by gregmoser** [comment]
I apologize, you are correct this isn't working on Account Address.

**Comment by davidpanzarella** [comment]
As of 4.3.007, layout is still an issue. No worries as values now save, but just wanted to communicate.

**Comment by rmarchandTen24** [comment]
https://github.com/ten24/slatwall/pull/4253

**Comment by rmarchandTen24** [comment]
https://github.com/ten24/slatwall/pull/4253
