### ISSUE TITLE
Account Address Custom Attributes Not Saving

### ISSUE THREAD

**Issue by davidpanzarella** [ten24/slatwall#4044]
When you try to save any custom account address attributes, they're not saving.

**Comment by davidpanzarella** [comment]
Any update on this?

**Comment by gregmoser** [comment]
Are all custom attributes no saving?  Or just checkboxes?

**Comment by davidpanzarella** [comment]
Only the checkboxes

**Comment by gregmoser** [comment]
On a fresh install of version 4.3 I can confirm that the checkboxes both display correctly and save.

**Comment by davidpanzarella** [comment]
So i'm not sure i get it. I'm on the latest 4.3.003, and i'm not getting things saved. Should i completely remove the entire slatwall folder except for the Custom directory, and try that? Also, you did test this on the account address custom attributes right? Did you happen to fill out all the fields? Hints, etc.

**Comment by gregmoser** [comment]
I apologize, you are correct this isn't working on Account Address.

**Comment by davidpanzarella** [comment]
Thanks Greg! Thought i was going crazy for a second. :)

**Comment by gregmoser** [comment]
This has now been resolved in version 4.3.005.  Please update, test and then close this issue once confirmed.

**Comment by davidpanzarella** [comment]
Working now! Thanks Gents!
