### ISSUE TITLE
Cannont read property 'length' of undefined

### ISSUE THREAD

**Issue by jsieber-aca** [ten24/slatwall#4248]
Operating System:	Windows 7
CFML Server:		ColdFusion Server: 10,0,18,296330
DB Dialect: 		MySQL
Slatwall Version:	4.3.011

When adding order items to an existing order the following error occurs in the console on each item added to the order after the first item. The error does not occur when adding the first item. This also causes a delay before refreshing the page.

`Uncaught TypeError: Cannot read property 'length' of undefined
listingDisplayUpdate @ global.js:1243
jQuery.ajax.success @ global.js:799
j @ jquery-1.7.1.min.js:2
k.fireWith @ jquery-1.7.1.min.js:2
x @ jquery-1.7.1.min.js:4
b @ jquery-1.7.1.min.js:4
Navigated to https://local.adventurecycling.org/Slatwall/?slatAction=entity.editorder&orderID=8a8a81235352a3e80153532c08f50075&s=1&fw1pk=3`

**Comment by rmarchandTen24** [comment]
https://github.com/ten24/slatwall/pull/4266
