### ISSUE TITLE
Price Groups not editable on Lucee 4.5.1

### ISSUE THREAD

**Issue by pauaware** [ten24/slatwall#4350]
Slatwall 4.3.025, Lucee 4.5.1, Mura 6.2.6539

On attempting to edit an existing Price Group the Slatwall is not finding the AccountsAssignedIDList.

![sw1](https://cloud.githubusercontent.com/assets/973097/14524493/bbc372ce-028c-11e6-80cc-accc104a6238.png)

Temporary fix by suppressing attempt to pull the Accounts List in 

/Slatwall/admin/views/entity/pricegrouptabs/assignedaccounts.cfm:

```
<cfoutput>
<!---
	<hb:HibachiListingDisplay smartList="#rc.priceGroup.getAccountsOptionsSmartList()#" multiselectFieldName="accounts" multiselectPropertyIdentifier="accountID" multiselectValues="#rc.priceGroup.getAccountsAssignedIDList()#" edit="#rc.edit#"> 
						      
		<hb:HibachiListingColumn propertyIdentifier="firstName" />
		<hb:HibachiListingColumn propertyIdentifier="lastName" />
		<hb:HibachiListingColumn tdclass="primary" propertyIdentifier="company" />
		<hb:HibachiListingColumn propertyIdentifier="primaryPhoneNumber.phoneNumber" />
		<hb:HibachiListingColumn propertyIdentifier="primaryEmailAddress.emailAddress" />
		<hb:HibachiListingColumn propertyIdentifier="guestAccountFlag" />
	
	</hb:HibachiListingDisplay>
--->
</cfoutput>
```

**Comment by pauaware** [comment]
If I revert Commit 3eaec61e2fabb0bc492c2af2a92462e7d1996867 then in assignedaccounts.cfm then functionality is restored.

New getAccountsAssignedIDList() breaks Lucee

**Comment by rmarchandTen24** [comment]
https://github.com/ten24/slatwall/pull/4369.

Looks like Lucee caught a scoping issue that CF is more forgiving of.

Should have this in 4.3.027

**Comment by pauaware** [comment]
Cheers Ryan, thanks for the follow up.
