### ISSUE TITLE
UPS Rates URL changed

### ISSUE THREAD

**Issue by Squeebly-Joe** [ten24/slatwall#4382]
The URL for UPS's rates API has changed. Simply changing to the new URL fixes the issue, but it cause the rates to be labeled twice (screenshot below).

Old URL: https://www.ups.com/ups.app/xml/Rate
New URL: https://onlinetools.ups.com/ups.app/xml/Rate

![screen shot 2016-04-20 at 12 26 19 pm](https://cloud.githubusercontent.com/assets/2466122/14682330/1fc4e5e0-06f3-11e6-90a8-7bf43afe38f0.png)

**Comment by gregmoser** [comment]
That image of the rates being displayed twice looks like it might be custom UI that you've added to the front-end of your site.  The default just uses whatever you call the "Shipping Method" when setting it up in the admin, we don't show provider specific naming.

With regards to the URL change we will certainly look into this and get it patched as soon as possible.

**Comment by Squeebly-Joe** [comment]
I would say too, but I've only updated the template to the Bootstrap 3 form-group markup. I'm trying to find where the double label coming from, but so far I'm only sure it's not in the checkout template or the UPS rates response.
