### ISSUE TITLE
Removal of / from TemplateService causing an issue

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#4910]
After b5796fa68d93dc130c4fbc25a53f38bc4fb3dc97 I'm getting a missing file error for email templates eg: "/Slatwallcustom/templates/email/order/confirmation.cfm"  Not sure if there is something missing further up the path building chain or if this should just be reverted.

**Comment by rmarchandTen24** [comment]
bug fix for this should be out in 4.5.015 later today
 





On Fri, Oct 14, 2016 10:40 AM, dzikakis notifications@github.com
wrote:
After b5796fa  I'm getting a missing file error for email templates eg:
"/Slatwallcustom/templates/email/order/confirmation.cfm" Not sure if there is
something missing further up the path building chain or if this should just be
reverted.

**Comment by sumitverma** [comment]
This has been resolved.
