### ISSUE TITLE
Hard error on shipping integration when http fails.

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#5123]
Noticed this in testing, we have call to slatAction=public:ajax.cart which was throwing a 500 every so often.

Stack trace:

Syntax Error, invalid Expression [Connection Failure] at lucee.runtime.interpreter.CFMLExpressionInterpreter.interpret(CFMLExpressionInterpreter.java:219):219 at lucee.runtime.interpreter.CFMLExpressionInterpreter.interpret(CFMLExpressionInterpreter.java:191):191 at lucee.runtime.functions.conversion.DeserializeJSON.call(DeserializeJSON.java:53):53 at lucee.runtime.functions.conversion.DeserializeJSON.call(DeserializeJSON.java:50):50 at integrationservices.baseshipping_cfc$cf.udfCall1(C:\Lucee\webapps\ROOT\Slatwall\integrationServices\BaseShipping.cfc:102):102 at integrationservices.baseshipping_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\integrationServices\BaseShipping.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216 at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:775):775 at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774 at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1603):1603 at integrationservices.ups.shipping_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\integrationServices\ups\Shipping.cfc:114):114 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at integrationservices.ups.shipping_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\integrationServices\ups\Shipping.cfc:99):99 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524 at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at model.service.shippingservice_cfc$cf.udfCall1(C:\Lucee\webapps\ROOT\Slatwall\model\service\ShippingService.cfc:160):160 at model.service.shippingservice_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\model\service\ShippingService.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at model.service.shippingservice_cfc$cf.udfCall2(C:\Lucee\webapps\ROOT\Slatwall\model\service\ShippingService.cfc:392):392 at model.service.shippingservice_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\model\service\ShippingService.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524 at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at slatwall.model.entity.orderfulfillment_cfc$cf.udfCall3(C:\Lucee\webapps\ROOT\Slatwall\model\entity\OrderFulfillment.cfc:360):360 at slatwall.model.entity.orderfulfillment_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\model\entity\OrderFulfillment.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216 at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:775):775 at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774 at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1603):1603 at org.hibachi.hibachiobject_cfc$cf.udfCall2(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiObject.cfc:121):121 at org.hibachi.hibachiobject_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiObject.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524 at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at org.hibachi.hibachitransient_cfc$cf.udfCall3(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiTransient.cfc:520):520 at org.hibachi.hibachitransient_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiTransient.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524 at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at org.hibachi.hibachiutilityservice_cfc$cf.udfCall3(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiUtilityService.cfc:235):235 at org.hibachi.hibachiutilityservice_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiUtilityService.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at org.hibachi.hibachiutilityservice_cfc$cf.udfCall3(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiUtilityService.cfc:263):263 at org.hibachi.hibachiutilityservice_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiUtilityService.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at org.hibachi.hibachiutilityservice_cfc$cf.udfCall3(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiUtilityService.cfc:226):226 at org.hibachi.hibachiutilityservice_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\HibachiUtilityService.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524 at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at model._transient.hibachiscope_cfc$cf.udfCall2(C:\Lucee\webapps\ROOT\Slatwall\model\transient\HibachiScope.cfc:299):299 at model._transient.hibachiscope_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\model\transient\HibachiScope.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524 at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at _public.controllers.ajax_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\public\controllers\ajax.cfc:74):74 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:643):643 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524 at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1778):1778 at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774 at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:768):768 at lucee.runtime.util.VariableUtilImpl.callFunction(VariableUtilImpl.java:729):729 at lucee.runtime.interpreter.ref.func.UDFCall.getValue(UDFCall.java:65):65 at lucee.runtime.interpreter.CFMLExpressionInterpreter.interpret(CFMLExpressionInterpreter.java:217):217 at lucee.runtime.functions.dynamicEvaluation.Evaluate._call(Evaluate.java:109):109 at lucee.runtime.functions.dynamicEvaluation.Evaluate.call(Evaluate.java:102):102 at lucee.runtime.functions.dynamicEvaluation.Evaluate.call(Evaluate.java:43):43 at org.hibachi.fw1.framework_cfc$cf.udfCall7(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\FW1\framework.cfc:1200):1200 at org.hibachi.fw1.framework_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\FW1\framework.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593 at org.hibachi.fw1.framework_cfc$cf.udfCall4(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\FW1\framework.cfc:680):680 at org.hibachi.fw1.framework_cfc$cf.udfCall(C:\Lucee\webapps\ROOT\Slatwall\org\Hibachi\FW1\framework.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524 at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761 at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:414):414 at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:223):223 at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:37):37 at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2265):2265 at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2228):2228 at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:456):456 at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:47):47 at javax.servlet.http.HttpServlet.service(HttpServlet.java:725):725 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291):291 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52):52 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239):239 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219):219 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106):106 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501):501 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142):142 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79):79 at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610):610 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88):88 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537):537 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085):1085 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658):658 at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222):222 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556):1556 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513):1513 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61):61 at java.lang.Thread.run(Thread.java:744):744

**Comment by sumitverma** [comment]
There is a setting under "Global Advanced Setting" --> "Display Integration Processing Errors"
If you set that to false it will suppress the error and display the default rate defined for the shipping method.

**Comment by dzikakis** [comment]
Excellent.  Would be nice if that setting cascaded so you could control
which integrations you're suppressing errors on.

Thanks!
