### ISSUE TITLE
JS Error on add account payment

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#5132]
Getting: http://errors.angularjs.org/1.5.5/ng/areq?p0=preprocessaccount_addaccountpayment&p1=not%20a%20function%2C%20got%20undefined

When trying to add an account payment .

UI obviously fails too:

![image](https://cloud.githubusercontent.com/assets/474990/21694460/69e7ef6e-d353-11e6-8a2f-dd4e8c4aa004.png)

**Comment by rmarchandTen24** [comment]
adding preprecossaccount_addaccountparyment back in by rmarchandTen24 · Pull
Request #5134 · ten24/slatwall

 This change is 

 github.com
 






On Thu, Jan 5, 2017 2:30 PM, dzikakis notifications@github.com
wrote:
Getting: 
http://errors.angularjs.org/1.5.5/ng/areq?p0=preprocessaccount_addaccountpayment&p1=not%20a%20function%2C%20got%20undefined

When trying to add an account payment .

UI obviously fails too:

**Comment by dzikakis** [comment]
Thanks!
