### ISSUE TITLE
Unable to deliver items on order fulfillment when payment type is term account

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#5133]
it looks like it's trying to capture a payment:

"There was an issue trying to capture the payments necessary to fulfill this order. Please review order payments and try again."

**Comment by rmarchandTen24** [comment]
fix will be in 4.5.030

**Comment by dzikakis** [comment]
Still seems to be an issue.. Think your comment was for the other issue, no code appears to have been changed around this.
