### ISSUE TITLE
Order items not showing.

### ISSUE THREAD

**Issue by robenr** [ten24/slatwall#5143]
![image](https://cloud.githubusercontent.com/assets/3232822/21725224/7c13016e-d45d-11e6-8377-4c46c19d906e.png)

Slatwall 4.5.030
Coldfusion 10

sw-order-item not getting looped

**Comment by robenr** [comment]
Is there any reason will AngularJS call be blocked in IIS?

**Comment by ten24git** [comment]
You will need to add JSON mime type in IIS.

**Comment by robenr** [comment]
<mimeMap fileExtension=".json" mimeType="application/json" />

is this you are referring to ?

**Comment by robenr** [comment]
`<mimeMap fileExtension=".json" mimeType="application/json" />`
`<httpErrors existingResponse="PassThrough" />`

to fix the error
