### ISSUE TITLE
Stripe integration - Sums all refunds

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#5226]
While doing the multiple return orders, I noticed the order totals were way out of wack..

https://github.com/ten24/slatwall/blob/master/integrationServices/stripe/Payment.cfc#L303-L306

This should only pull the last refunded amount. As-is it's summing up all previous refunds and attributing them to this individual credit transaction.

**Comment by rmarchandTen24** [comment]
missing var scope by rmarchandTen24 · Pull Request #5227 · ten24/slatwall This
change is  github.com  






On Fri, Jan 27, 2017 9:25 PM, dzikakis notifications@github.com  wrote:
While doing the multiple return orders, I noticed the order totals were way out
of wack..

https://github.com/ten24/slatwall/blob/master/integrationServices/stripe/Payment.cfc#L303-L306

This should only pull the last refunded amount. As-is it's summing up all
previous refunds and attributing them to this individual credit transaction.

**Comment by dzikakis** [comment]
Good catch on the Var, but that's not the problem unfortunately.

Eg the request 
/v1/charges/ch_19glZN2GzuWRU76gIHHJw0mS/refund

With body of: {
  "amount": "3700"
} 

so a $37 refund.

returns this:

{
  "id": "ch_19glZN2GzuWRU76gIHHJw0mS",
  "object": "charge",
  "amount": 37995,
  "amount_refunded": 23199,
  "application": null,
  "application_fee": null,
  "balance_transaction": "txn_19glaH2GzuWRU76gf3Tv6nzq",
  "captured": true,
  "card": {
    "id": "card_19glZL2GzuWRU76gVivUUmGG",
    "object": "card",
    "address_city": "Kingston",
    "address_country": "CA",
    "address_line1": "222 test street",
    "address_line1_check": "pass",
    "address_line2": null,
    "address_state": "ON",
    "address_zip": "K7K7E6",
    "address_zip_check": "pass",
    "brand": "Visa",
    "country": "US",
    "customer": "cus_A0n94MgETnFTaN",
    "cvc_check": "pass",
    "dynamic_last4": null,
    "exp_month": 3,
    "exp_year": 2017,
    "fingerprint": "8iCtRQ7QgLFEfiBg",
    "funding": "credit",
    "last4": "4242",
    "metadata": {},
    "name": "Dave",
    "tokenization_method": null,
    "type": "Visa"
  },
  "created": 1485569041,
  "currency": "cad",
  "customer": "cus_A0n94MgETnFTaN",
  "description": "Product 1",
  "destination": null,
  "dispute": null,
  "failure_code": null,
  "failure_message": null,
  "fraud_details": {},
  "invoice": null,
  "livemode": false,
  "metadata": {
    "orderPayment_id": "ff80818159e1d6f30159e2d09ada005d",
    "transaction_id": "ff80818159e1d6f30159e2d0a1010061",
    "account_id": "ff80818159e1d6f30159e2cd6aac0022",
    "account_firstName": "Test",
    "account_lastName": "Testerson",
    "account_phoneNumber": "999-999-9999",
    "account_emailAddress": "test1@test..com",
    "billing_name": "Test",
    "order_id": "ff80818159e1d6f30159e2cd6c400025",
    "orderItem_1_quantity": "10",
    "orderItem_1_skuCode": "PRD-1"
  },
  "order": null,
  "outcome": {
    "network_status": "approved_by_network",
    "reason": null,
    "risk_level": "normal",
    "seller_message": "Payment complete.",
    "type": "authorized"
  },
  "paid": true,
  "receipt_email": null,
  "receipt_number": null,
  "refunded": false,
  "refunds": [
    **{
      "id": "re_19gxQY2GzuWRU76gWpVOawbg",
      "object": "refund",
      "amount": 3700,
      "balance_transaction": "txn_19gxQY2GzuWRU76gpwEmKfvS",
      "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
      "created": 1485614622,
      "currency": "cad",
      "metadata": {},
      "reason": null,
      "receipt_number": null,
      "status": "succeeded"
    },
    {
      "id": "re_19glzW2GzuWRU76gBem0Qm1V",
      "object": "refund",
      "amount": 3700,
      "balance_transaction": "txn_19glzX2GzuWRU76gx43aRFrC",
      "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
      "created": 1485570662,
      "currency": "cad",
      "metadata": {},
      "reason": null,
      "receipt_number": null,
      "status": "succeeded"
    },
    {
      "id": "re_19glzU2GzuWRU76gNrV5Mw76",
      "object": "refund",
      "amount": 3700,
      "balance_transaction": "txn_19glzV2GzuWRU76g2RPZ1J46",
      "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
      "created": 1485570660,
      "currency": "cad",
      "metadata": {},
      "reason": n
 [
    {
      "id": "re_19gxQY2GzuWRU76gWpVOawbg",
      "object": "refund",
      "amount": 3700,
      "balance_transaction": "txn_19gxQY2GzuWRU76gpwEmKfvS",
      "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
      "created": 1485614622,
      "currency": "cad",
      "metadata": {},
      "reason": null,
      "receipt_number": null,
      "status": "succeeded"
    },
    {
      "id": "re_19glzW2GzuWRU76gBem0Qm1V",
      "object": "refund",
      "amount": 3700,
      "balance_transaction": "txn_19glzX2GzuWRU76gx43aRFrC",
      "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
      "created": 1485570662,
      "currency": "cad",
      "metadata": {},
      "reason": null,
      "receipt_number": null,
      "status": "succeeded"
    },
    {
      "id": "re_19glzU2GzuWRU76gNrV5Mw76",
      "object": "refund",
      "amount": 3700,
      "balance_transaction": "txn_19glzV2GzuWRU76g2RPZ1J46",
      "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
      "created": 1485570660,
      "currency": "cad",
      "metadata": {},
      "reason": null,
      "receipt_number": null,
      "status": "succeeded"
    },
    {
      "id": "re_19glkY2GzuWRU76gfKxNDDVE",
      "object": "refund",
      "amount": 3700,
      "balance_transaction": "txn_19glkY2GzuWRU76gcAacTqH4",
      "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
      "created": 1485569734,
      "currency": "cad",
      "metadata": {},
      "reason": null,
      "receipt_number": null,
      "status": "succeeded"
    },
    {
      "id": "re_19glcb2GzuWRU76gM70imiNU",
      "object": "refund",
      "amount": 3700,
      "balance_transaction": "txn_19glcc2GzuWRU76gaP9MGq7p",
      "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
      "created": 1485569241,
      "currency": "cad",
      "metadata": {},
      "reason": null,
      "receipt_number": null,
      "status": "succeeded"
    },
    {
      "id": "re_19glbi2GzuWRU76gugMrpt3h",
      "object": "refund",
      "amount": 4699,
      "balance_transaction": "txn_19glbj2GzuWRU76ghC0zmfIk",
      "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
      "created": 1485569186,
      "currency": "cad",
      "metadata": {},
      "reason": null,
      "receipt_number": null,
      "status": "succeeded"
    }**
  ],
  "review": null,
  "shipping": null,
  "source": {
    "id": "card_19glZL2GzuWRU76gVivUUmGG",
    "object": "card",
    "address_city": "Kingston",
    "address_country": "CA",
    "address_line1": "222 Test st",
    "address_line1_check": "pass",
    "address_line2": null,
    "address_state": "ON",
    "address_zip": "K7K7E6",
    "address_zip_check": "pass",
    "brand": "Visa",
    "country": "US",
    "customer": "cus_A0n94MgETnFTaN",
    "cvc_check": "pass",
    "dynamic_last4": null,
    "exp_month": 3,
    "exp_year": 2017,
    "fingerprint": "8iCtRQ7QgLFEfiBg",
    "funding": "credit",
    "last4": "4242",
    "metadata": {},
    "name": "Test",
    "tokenization_method": null,
    "type": "Visa"
  },
  "source_transfer": null,
  "statement_descriptor": null,
  "status": "paid",
  "statement_description": null
}

And the integration is summing up all of those refunds under one transaction so the credit on the original order is HUGE in slatwall.

Was just thinking, I don't know if we can rely on the order of the refunds to determine the last one. Then checked the API documentation.. I don't think the endpoint being used is ideal.  It should be http://api.stripe.com/v1/refunds   -  [https://stripe.com/docs/api#create_refund](https://stripe.com/docs/api#create_refund) which returns a nice clean response:

{
  "id": "re_19gxqO2GzuWRU76g93FrRI0R",
  "object": "refund",
  "amount": 3700,
  "balance_transaction": "txn_19gxqP2GzuWRU76goW4C7i04",
  "charge": "ch_19glZN2GzuWRU76gIHHJw0mS",
  "created": 1485616224,
  "currency": "cad",
  "metadata": {},
  "reason": null,
  "receipt_number": null,
  "status": "succeeded"
}

Thoughts? I can make this change if everyone is in agreement.
