### ISSUE TITLE
Manually Edited Price Gets Overridden 

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#5274]
If you add an item to an order in the admin (as super) with a manually set price that it higher than the price group rate it gets bumped back down to the group rate. Expected behavior would be that any manually set price would stay - correct?

**Comment by gregmoser** [comment]
Yes, this is correct.  @sumitverma this is the functionality I was talking about before where we need to be able to override prices in the admin. @dzikakis can you confirm that on your previous version of Slatwall that functionality was in place?

**Comment by dzikakis** [comment]
@gregmoser I can't confirm this specific case from previous versions. If you set the price _lower_ than what they would get by default from the pricegroup it sticks, but it seems it only takes the lower value of the two.  Maybe there needs to be a flag on the order item adminSetPriceFlag or similar, so later on calculation processes know not to mess with it?
