### ISSUE TITLE
Rounding issues on return/exchange orders

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#5275]
Have seen this in a few places dealing with payments on returns:

![image](https://cloud.githubusercontent.com/assets/474990/23006035/88a89c92-f3cd-11e6-9713-329c360eff5a.png)

**Comment by gregmoser** [comment]
@rmarchandTen24 I have some concerns that this might be the new precisionEvaluate() replacement function.

**Comment by dzikakis** [comment]
@gregmoser @rmarchandTen24  actually it isn't due to that. I haven't updated to where that was introduced just yet. Perhaps that change might even have correct this?  I have a couple mods I made to core to correct immediate issues, so I just need to find time to merge up to the latest and then I can test with that precisionEval replacement
