### ISSUE TITLE
Create Product Bundle failing

### ISSUE THREAD

**Issue by nsollecito** [ten24/slatwall#5288]
We're working with product bundles and trying to create a new bundle but getting a validation error when defining the Bundle Group on our test server, Slatwall version 4.5.033

![screen shot 2017-02-21 at 3 21 41 pm](https://cloud.githubusercontent.com/assets/1014995/23183281/83707008-f849-11e6-8213-df9f9cc0e4d9.png)

However, we just discovered this seems to be working on 4.5.020.. We'll add any other details to this issue as we come across them.

**Comment by sumitverma** [comment]
This is resolved in current version (5+)
