### ISSUE TITLE
No-Qualifier promotion items added to cart at $0

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#5296]
Set up a no-qualifier promotion for 60% off, and people were able to add to their cart for $0 - or $.49 (due to rounding rule)

**Comment by dzikakis** [comment]
Additionally.. it was applying to the retail price on pricegroup orderitems..

So a retail priced item of 34.99 with a pricegroup price of 17.50 was getting discounted $20.99 !

There is no record for this in swpromorewardeligiblepricegrp either

**Comment by gregmoser** [comment]
@rmarchandTen24 and @sumitverma these seems like a critical issue that we need to get resolved asap.

**Comment by dzikakis** [comment]
My temporary work-around was to add an order qualifier of qty=1, which works. The sale price doesn't show up in the product listings though. I've opted not to clear the display cache at the moment so it still has the appearance we want.
