### ISSUE TITLE
Stock records created in inventory tab views when expanding location hierarchy

### ISSUE THREAD

**Issue by chriskent** [ten24/slatwall#5516]
Stock records are created when expanding the locations in the inventory tab view for skus and stocks for all sku/location combinations. 

This means that you cannot identify the actual sku/location combinations that you have set up via stock receipts. 

Tested on latest version of Slatwall 4.5.050 

- Clean install
- Create many locations including nested locations
- Add product, set sku to track inventory
- Do a "manual in stock adjustment" to receive stock into a selected location
At this point one stock record exists that is correct.

View sku or stock entity and expand inventory tab, then expand the location hierarchy. 
Multiple stock records will now exist for all combinations of sku and locations. Which means you cannot perform a sku().getStocks() or location().getStocks() and just get the true stocks for either skus or locations.

**Comment by sumitverma** [comment]
@chriskent That is by design. A record for stock can exist but, you need to look at the different quantity values at location to figure out availability.

**Comment by chriskent** [comment]
Seems strange. Found this while working on the Cycle Count. e.g. for a sku.getStocks() to get the locations that the sku is stored in. 

But, if stock records are created by design for sku/location combinations that have never held stock for the sku then would need to drill down to inventory as well to determine whether the sku has been stocked at the the locations. 

Had thought about excluding 0 quantity, e.g. QOH=0 stock records, but not sure if it is OK to exclude a stock record just because it has 0 QOH.
A scenario that I have seen in the past (many years ago and not Slatwall) where a sku is in multiple locations and pickers take the stock from the wrong location and not recording this different location on pick confirm. 
This can lead to ghost physical stock in locations that the warehouse management system believes have been fully used where all stock quantity values become 0 and being out of sync with the actual physical stock.

**Comment by sumitverma** [comment]
if you use stock.hasInventory that will tell you if this location was/is used to store inventory. If there was any inventory transaction, that will return true. That's pretty much same as checking if stock record exists.
