### ISSUE TITLE
Javascript error on bundle products fresh install

### ISSUE THREAD

**Issue by Yamaha32088** [ten24/slatwall#5650]
There is an error with a fresh quick-start docker install on the bundle products page. I get the following error: 
![image](https://user-images.githubusercontent.com/6120946/29411920-5b1543f0-831c-11e7-9b76-44af20749298.png)

**Comment by damienbkx** [comment]
Same error for me.
Adding other product types works OK, Only adding bundle product is generating the error

My config
- Ubuntu 16.04.3
- Lucee 5.2.3.35
- MySql 5.7.19
- Mura 7.0.70.37
- Slatwall 5.1.007

Thanks
