### ISSUE TITLE
error on install 

### ISSUE THREAD

**Issue by AppareFujiyama** [ten24/slatwall#5747]
Installation of  Slatwall Plugin for Mura CMS 7 fails.

**[System Requirements]**
Slatwall-mura-master (Latest commit 7e 9 b 70 a on 15 Oct 2016)
[slatwall-mura](https://github.com/ten24/slatwall-mura)
Coldfusion 2016 developer (2016.0.03.301771)
Database: MSSQL2014 Express
(MySQL Comunity 5.5.57 / MySQL Community 5.7.19 etc.)
Mura CMS 7.0.7034
Windows 7 professional sp 1 64 bit
IIS 7.5
*The authority(permission) of the file has already been confirmed.

**[Situation]**
Immediately after installation, the following error is output.
- - -
There was an unexpected error while processing your request.
Please notify your system administrator.

To see errors, add the following line to /Slatwall/custom/config/configFramework.cfm:

`<cfset` variables.framework.hibachi.errorDisplayFlag = true />

To have errors emailed you can add the following line to /Slatwall/custom/config/configFramework.cfm:

`<cfset` variables.framework.hibachi.errorNotifyEmailAddresses = "admin 1 @ mysite.com, admin 2 @ mysite.com" />

- - -
There is no "configFramework.cfm" file in Slatwall / custom / config /.
If you create "configFramework.cfm" in "Slatwall / custom / config /" and set it by writing
`"<cfset = variables.framework.hibachi.errorDisplayFlag = true />", this error disappears.

However, after rebooting, clicking [MuraCMS] - [Plugins] - [Slatwall] will generate an error. 
[error_file.zip](https://github.com/ten24/slatwall/files/1326321/error_file.zip)

**Comment by AppareFujiyama** [comment]
If it does not work on "MuraCMS 7", "Slatwall" should be deleted from introduction of plugin of "MuraCMS 7" website. I wasted a lot of time.

**Comment by tdhatcher** [comment]
Slatwall and Mura 7 work together.

What version of coldfusion are your running on? It is having an issue with database connection. Could possibly be trying to use incorrect datasource or one that doesn't exist.

Likely just a configuration setting to fix the problem.

**Comment by tdhatcher** [comment]
Are you meeting the minimum system requirements?

### System Requirements

- _CFMLServer_: **Coldfusion 9.0.1+**, Railo 4.0.1.003+, Lucee 4.5+
- _Database Engine_: MySQL, Microsoft SQL or Oracle
- _Operating System_: Windows, Mac OSX, Linux

```
java.sql.SQLDataException: [Macromedia][SQLServer JDBC Driver][SQLServer]文字列データまたはバイナリ データが切り捨てられます。 at macromedia.jdbc.sqlserverbase.ddcw.b(Unknown Source) at macromedia.jdbc.sqlserverbase.ddcw.a(Unknown Source) at macromedia.jdbc.sqlserverbase.ddcv.b(Unknown Source) at macromedia.jdbc.sqlserverbase.ddcv.a(Unknown Source) at macromedia.jdbc.sqlserver.tds.ddr.v(Unknown Source) at macromedia.jdbc.sqlserver.tds.ddr.a(Unknown Source) at macromedia.jdbc.sqlserver.tds.ddq.a(Unknown Source) at macromedia.jdbc.sqlserver.tds.ddr.c(Unknown Source) at macromedia.jdbc.sqlserver.dda3.m(Unknown Source) at macromedia.jdbc.sqlserverbase.dde7.e(Unknown Source) at macromedia.jdbc.sqlserverbase.dde7.a(Unknown Source) at macromedia.jdbc.sqlserverbase.ddd2.a(Unknown Source) at macromedia.jdbc.sqlserverbase.dde7.x(Unknown Source) at macromedia.jdbc.sqlserverbase.dde7.z(Unknown Source) at macromedia.jdbc.sqlserverbase.ddd2.executeUpdate(Unknown Source) at macromedia.jdbc.sqlserverbase.ddd6.executeUpdate(Unknown Source) at coldfusion.server.j2ee.sql.JRunPreparedStatement.executeUpdate(JRunPreparedStatement.java:96)
```

**Comment by AppareFujiyama** [comment]
Dear Todd Hatcher

Thank you for the reply.
Of course, the requirement is satisfied.
---
CFMLServer: Coldfusion 2016 developer (2016.0.03.301771)
Database Engine: Microsoft SQL2014 Express
Operating System:Windows 7 professional sp 1 64 bit
---
But, There is one place to worry about.
I installed it in Japanese environment. Is there a possibility that the Japanese environment caused the database field to exceed the specified number of bytes?
In that case, do you know how to identify which database field is the cause?

Yours sincerely,
Fujiyama
