### ISSUE TITLE
On MSSQL Platforms Varchar(X) fields should be created as varchar(MAX) where X is greater than or equal to 4,000

### ISSUE THREAD

**Issue by k1n6** [ten24/slatwall#5797]
Versions of SQL server will store the data appropriately for the size of the data in the field - it will be stored in the table data for values less than 4,000 or 8,000 and an external reference created for larger values.

Fields like [data] in the [SWAudit] table have to be modified or slatwall does not run properly - most specifically when any attribute (say a WYSIWYG attribute on a product) exceeds 4,000 characters.  There are other field as well.

As another user in the groups pointed, out, you can use this query to find them (replacing <databasename> with the name of your database):

`SELECT *
FROM information_schema.columns where data_type = 'varchar'
AND table_catalog = '<databasename>'
AND CHARACTER_OCTET_LENGTH >= 4000 ORDER BY table_name DESC`

**Comment by cjwilson3759** [comment]
I'm the other user in the [groups ](https://mail.google.com/mail/u/0/#search/slatwall/15eeec63a1509015) which @k1n6 referenced. I thought I would add some additional code to this post that might better pinpoint and help others. 

So I decided to do a fresh install of Mura CMS and then load fresh install of Slatwall using the plugin for Mura CMS (https://github.com/ten24/slatwall-mura). 

Again, I ran into same error messaged "String or binary data would be truncated." as before without any indication of what table columns needed data types changed to varchar(max).  I'm using Microsoft SQL Server. Only this time I thought, "Screw this" on seeking out and manually changing data type. So I wrote the new query below to generate the TSQL code to assist. 

Instructions: select all, copy n paste to a "New Query" window, run, then done..


```
SELECT 'ALTER TABLE [' + TABLE_SCHEMA + '.' + TABLE_NAME + '] ALTER COLUMN [' + COLUMN_NAME + '] VARCHAR(MAX);' AS QUERY
FROM information_schema.columns where data_type = 'varchar'
AND table_catalog = '<YOUR DATABASE NAME>'
AND CHARACTER_OCTET_LENGTH > 4000 ORDER BY table_name DESC;
```


The above query generated the ALTER statements on 31 rows below.

```
ALTER TABLE [SwType] ALTER COLUMN [typeIDPath] VARCHAR(MAX);
ALTER TABLE [SwType] ALTER COLUMN [typeDescription] VARCHAR(MAX);
ALTER TABLE [SwToDo] ALTER COLUMN [description] VARCHAR(MAX);
ALTER TABLE [SwTask] ALTER COLUMN [taskConfig] VARCHAR(MAX);
ALTER TABLE [SwSku] ALTER COLUMN [skuDescription] VARCHAR(MAX);
ALTER TABLE [SwSetting] ALTER COLUMN [settingValue] VARCHAR(MAX);
ALTER TABLE [SwReport] ALTER COLUMN [metrics] VARCHAR(MAX);
ALTER TABLE [SwReport] ALTER COLUMN [dimensions] VARCHAR(MAX);
ALTER TABLE [SwPromotion] ALTER COLUMN [promotionDescription] VARCHAR(MAX);
ALTER TABLE [SwProductType] ALTER COLUMN [productTypeIDPath] VARCHAR(MAX);
ALTER TABLE [SwProductType] ALTER COLUMN [productTypeDescription] VARCHAR(MAX);
ALTER TABLE [SwProductReview] ALTER COLUMN [review] VARCHAR(MAX);
ALTER TABLE [SwProduct] ALTER COLUMN [productDescription] VARCHAR(MAX);
ALTER TABLE [SwPrintTemplate] ALTER COLUMN [printContent] VARCHAR(MAX);
ALTER TABLE [SwPriceGroup] ALTER COLUMN [priceGroupIDPath] VARCHAR(MAX);
ALTER TABLE [SwPaymentTransaction] ALTER COLUMN [message] VARCHAR(MAX);
ALTER TABLE [SwOrderItemGiftRecipient] ALTER COLUMN [giftMessage] VARCHAR(MAX);
ALTER TABLE [SwOptionGroup] ALTER COLUMN [optionGroupDescription] VARCHAR(MAX);
ALTER TABLE [SwOption] ALTER COLUMN [optionDescription] VARCHAR(MAX);
ALTER TABLE [SwImage] ALTER COLUMN [imageDescription] VARCHAR(MAX);
ALTER TABLE [SwFile] ALTER COLUMN [fileDescription] VARCHAR(MAX);
ALTER TABLE [SwEmailTemplate] ALTER COLUMN [emailBodyHTML] VARCHAR(MAX);
ALTER TABLE [SwEmailTemplate] ALTER COLUMN [emailBodyText] VARCHAR(MAX);
ALTER TABLE [SwContent] ALTER COLUMN [contentIDPath] VARCHAR(MAX);
ALTER TABLE [SwContent] ALTER COLUMN [titlePath] VARCHAR(MAX);
ALTER TABLE [SwContent] ALTER COLUMN [urlTitle] VARCHAR(MAX);
ALTER TABLE [SwComment] ALTER COLUMN [comment] VARCHAR(MAX);
ALTER TABLE [SwCategory] ALTER COLUMN [categoryIDPath] VARCHAR(MAX);
ALTER TABLE [SwCategory] ALTER COLUMN [categoryDescription] VARCHAR(MAX);
ALTER TABLE [SwAttributeValue] ALTER COLUMN [attributeValue] VARCHAR(MAX);
ALTER TABLE [SwAttribute] ALTER COLUMN [attributeDescription] VARCHAR(MAX);
```

**Comment by Ivan-McA** [comment]
@cjwilson3759 that link is to your Gmail.
