### ISSUE TITLE
isAddressInZoneByZoneID() method missing

### ISSUE THREAD

**Issue by howellcc** [ten24/slatwall#7096]
The TaxService.cfc has 3 references to getAddressService().isAddressInZoneByZoneID(). 
This method doesn't exist.

**Comment by sumitverma** [comment]
Can you please post a link to the line number?

**Comment by howellcc** [comment]
Sure!
https://github.com/ten24/slatwall/blob/2c75b35386af107c4abc8b2812f703cdeb8028b9/model/service/TaxService.cfc#L189
https://github.com/ten24/slatwall/blob/2c75b35386af107c4abc8b2812f703cdeb8028b9/model/service/TaxService.cfc#L352
https://github.com/ten24/slatwall/blob/2c75b35386af107c4abc8b2812f703cdeb8028b9/model/service/TaxService.cfc#L487

**Comment by sumitverma** [comment]
Thanks @howellcc! Can you please email me, so I can send you contributor agreement?

**Comment by jasperboyd** [comment]
Hey @howellcc thank you! See PR #7098

**Comment by jasperboyd** [comment]
I built a bit on your fix so we can pass in either `addressZone` or `addressZoneID`
