### ISSUE TITLE
Admin Backend / Empty pages after fresh setup

### ISSUE THREAD

**Issue by MarcAckermann** [ten24/slatwall#7115]
I just made a fresh slatwall setup on my dev enviroment. 
When I login to the backend all the screens like 'Countries', 'Currencies' etc are empty. The default values are existing in the db tables. I added a new country but the screen is still empty.
Am I missing something on setting up slatwall or is the current release broken?

Running on
Lucee 5.3.6.61
MS SQL Server 2019
File used for setup: https://github.com/ten24/slatwall/archive/master.zip

![Screenshot 2020-11-02 134809](https://user-images.githubusercontent.com/1645475/97870592-75a0f900-1d13-11eb-83fb-75a83da34f22.jpg)

**Comment by sumitverma** [comment]
@MarcAckermann can you please inspect element on the page and see if there is any JS error?

**Comment by MarcAckermann** [comment]
I don't see  any js errors. 

![Screenshot 2020-11-02 173937](https://user-images.githubusercontent.com/1645475/97894229-90369a80-1d32-11eb-8449-95c9cd497c20.jpg)

Is the content of the page (the countries) supposed to be loaded directly or with an js ajax call? Right now there is just a <span> in the page source:

![Screenshot 2020-11-02 174334](https://user-images.githubusercontent.com/1645475/97894925-6762d500-1d33-11eb-8841-ac7e2040991e.jpg)

**Comment by MarcAckermann** [comment]
Actually it looks like there is an js error:

![Screenshot 2020-11-02 175437](https://user-images.githubusercontent.com/1645475/97896076-e1478e00-1d34-11eb-84c8-7855772535b0.jpg)

**Comment by MarcAckermann** [comment]
It looks like I fixed the problem for the moment: On gettings familiar with slatwall I found the "Create Json" option under the Tools menu. I clicked this selection and after a minute of wait, some magical seems to happened in the backgound that fixed it.
Would be nice of you would add this to the setup script.
