### ISSUE TITLE
Issue in slatwall default templates for mura

### ISSUE THREAD

**Issue by MarcAckermann** [ten24/slatwall#7116]
I made a new setup with a mura site and the slatwall-mura-master plugin. 
The default slatwall pages and templates were created in the installation process.
When I click on the frontend page 'Product Listing' or any other slatwall pages in the frontend the following error is thrown:

**500 Error
can't call method [getAppName] on object, object is null
Code:0
Type:expression

lucee.runtime.exp.ExpressionException: can't call method [getAppName] on object, object is null

	at lucee.runtime.reflection.Reflector.callMethod(Reflector.java:871)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:829)

	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)

	at themes._default.templates._slatwall_header_cfm450$cf.call(/muraWRM/themes/default/templates/_slatwall-header.cfm:77)**

Full error stack here:
[mura-slatwall-issue.txt](https://github.com/ten24/slatwall/files/5475956/mura-slatwall-issue.txt)

In _slatwall-header.cfm:77 what is the var 'customPartialsPath' for? 

Beside the method error the only partials folder I could find is \themes\default\scss\site\partials.
So /templates/partials/ in line 77 also would not work,

My setup:
mura 7.1
Lucee 
MS SQL Server 2019

**Comment by MarcAckermann** [comment]
A little further investigation:
**$.slatwall.getSite().getSiteName()**  
is working fine in this template and outputs "Default".

But there's a problem with 
$.slatwall.getSite().getApp().getAppName()

**Comment by MarcAckermann** [comment]
Ok, reason is that the database table 
dbo.SwApp 
is empty. What is this for?
And also what is the 'customPartialsPath' for?

**Comment by sumitverma** [comment]
@MarcAckermann $.slatwall.getSite().getApp().getAppName() is used for Slatwall CMS. If you are using Mura you don't need that. When using Slatwall CMS, you create and "App" and then assign site to that app.
