### ISSUE TITLE
Add ability to define custom image naming schema

### ISSUE THREAD

**Issue by sumitverma** [ten24/slatwall#920]
i.g: {productCode}-{imageOptionGroupCodeString}

**Comment by sumitverma** [comment]
Implemented in 4.2

**Comment by gregmoser** [comment]
Where / how was this implemented?  How are we able to do this?

**Comment by sumitverma** [comment]
There is a sku setting called skuDefaultImageNamingConvention

https://github.com/ten24/slatwall/blob/master/model/service/SettingService.cfc#L256

**Comment by gregmoser** [comment]
Looks like the default has a space in the filename... i think that this should by default be a dash.

Also, the sku property is "addOptionCodes" when that doesn't seem correct either, shouldn't this be "allImageOptionCodes" or something to that effect sense all option codes would mean both the ones flagged as image options and those that aren't.

**Comment by ten24git** [comment]
All spaces are replaced by dash automatically.

Sure, we can change the string replace variable to "allImageOptionCodes".
You can add a task for it.

Sumit Verma
Partner / Vice President | ten24, LLC
office: 877.886.5806 x 103 | mobile: 617.290.8214
www.ten24web.com | www.linkedin.com/in/sverma | twitter: blogonria

**Comment by gregmoser** [comment]
I just went ahead and added a PR for the tweeks... it was quicker than writing up a task:
https://github.com/ten24/slatwall/pull/3910
