### ISSUE TITLE
Generic Import Utility

### ISSUE THREAD

**Issue by gregmoser** [ten24/slatwall#960]
This would allow you to:
- Create an Import Job
- Allow for the source file to be a local file, remote url, ftp source, or manual upload
- Allow for this Job to be scheduled as a task
- Map the source columns to destinations and save that mapping to the job

**Comment by rwatts3** [comment]
Hi @gregmoser was this implemented in a newer please of slatwall ? Can't seem to find the functionality anywhere ?

**Comment by gregmoser** [comment]
There is currently no UI for generic import.  However there is some code in the core application that can help with import.  I recommend searching 'import' in the community forum here: 

http://www.slatwallcommerce.com/community
